#!/bin/sh

# some system has unusable vi
alias v=vim
alias iv=vim
alias vi=vim
alias vs="vim patches/series"
alias t="vim -t"

alias sc='sort | uniq -c | sort -nr | more'

alias path='echo -e ${PATH//:/\\n}'

# nr_cpu=$(grep -c processor /proc/cpuinfo)
nr_cpu=$(nproc)
alias make="make -j$nr_cpu"

alias route="route -n"

alias l='less -R'
alias s=ssh
alias x=startx
alias q=quilt
# alias j=guilt # j for Jeff :)
# alias b=bzr
# alias s=svn
alias ff=firefox

alias u="uname -a"

alias gu="git remote update" # && git checkout origin/master"
alias gs="git show --format=fuller --stat --patch"
alias gl="git log --format=fuller"
alias gd="git diff"
alias gc="git checkout"
#alias gca="git commit -as"
alias gg="git grep --color -n"
alias gr="git rebase HEAD~10"
alias grc="git rebase --continue"

alias gpr="git pull --rebase"
alias gau="git add -u"
alias gcs="git commit -s"
alias gca="git commit --amend"
alias glp="git log -p"

alias sx='screen -x'

alias dm="dmesg| less"
alias dt="dmesg| tail -n 20"
alias dg="dmesg| grep -Ei"

# open my email outbox at ~/Mail/archive/outbox
alias o='mutt -f \<'

alias diffstat='diffstat -p1 -w70'
alias trueprint='trueprint --no-cover-sheet --no-file-index --no-page-break-after-function --ignore-form-feeds --no-holepunch --top-holepunch --no-page-furniture-lines --no-braces-depth --no-headers -3 --output -'

alias arp='arp -n'

alias grep='grep --color --exclude=cscope.out --exclude=tags'
if [[ -x /usr/bin/glark ]]; then
        alias g='glark --binary-files=without-match'
        alias gr='glark -r --binary-files=without-match'
        alias gi='glark -i --binary-files=without-match'
        alias gir='glark -ir --binary-files=without-match'
else
        alias g='grep -E -I'
        alias gi='grep -E -Ii'
        alias gr='grep -E -Ir'
        alias gir='grep -E -Iir'
fi

# grep file
alias gf='find . -type f -print0 | xargs -0 grep -E'
# grep the history
alias gh='history 0 | grep -E'

alias du='du -h'
alias tree='tree -N'
alias free='free -m'

# fake user-agent of wget
alias wget-ua='wget --user-agent="Mozilla/4.0 (compatible; DAU 9.0; Wixdows NT 5.5; DT)"'
#alias wget='tsocks wget --restrict-file-names=nocontrol'
# alias mirror="wget --mirror --no-parent --convert-links --restrict-file-names=nocontrol"
# alias mirror2="wget -m -p -np"

alias last='last | head -n $(( +LINES ? LINES - 4 : 20 ))'

# disk/memory/package space eaters
alias sd="find -maxdepth 1 -print0 |xargs -0i du -ks {} |sort -rn |head -11 | cut -f2 | xargs -i du -hs {}"
alias sm='ps aux --sort=rss'
alias sp='dpkg-query -W --showformat='\''${Installed-Size} ${Package}\n'\'' | sort -n'

alias p='ps aux|less'
alias pse='ps -eo user,pid,tid,class,rtprio,ni,pri,psr,pcpu,vsz,rss,pmem,stat,wchan:28,cmd|less'
alias pss='processes=`ps aux`; echo "$processes" | head -n1; echo "$processes" |grep -E'

[[ $USER = 'root' ]] && alias ai='apt-get install' \
                     || alias ai='sudo apt-get install'
[[ $USER = 'root' ]] && alias au='apt-get update' \
                     || alias au='sudo apt-get update'
[[ $USER = 'root' ]] && alias auu='apt-get update && apt-get upgrade' \
                     || alias auu='sudo apt-get update && sudo apt-get upgrade'
# alias ac='apt-cache'
# alias ad='apt-cache show'
alias as='apt-cache search'
alias asn='apt-cache search --names-only'
alias af='apt-file'
alias dl='dpkg -l'
# alias dL='dpkg -L'
[[ -x /usr/bin/dlocate ]] && alias ds='dlocate -S' \
                          || alias ds='dpkg -S'

alias ucat='iconv -f utf8 -t gbk'
alias gcat='iconv -t utf8 -f gbk'
alias ulang='LANG=zh_CN.UTF-8'
alias glang='LANG=zh_CN.GBK'

if [[ $LANG == "zh_CN.UTF-8" ]]; then
        alias m='LANG=zh_CN.GBK man'
	# alias i='LANG=zh_CN.GBK pinfo'
        alias luit='LANG=zh_CN.GBK luit -encoding GBK'
        alias xmms='LANG=zh_CN.GBK xmms'
else
        alias m='man'
	# alias i='pinfo'
fi


alias ls='ls -h --color=auto --show-control-chars'
alias sl='ls'
alias la='ls -A'
alias ll='ls   -lrt --color=auto --time-style=long-iso'
alias lla='ls -Alrt --color=auto --time-style=long-iso'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'


#alias xdvi='xdvi -s 5 -expert'

alias md='mkdir -p'
alias rd=rmdir
alias d='dirs -v'
#alias j='jobs -l'
alias lo=locate

alias mutt='cd ~/Mail; mutt'
# configure
# alias CO="./configure"
# alias CH="./configure --help"

mkdir -p ~/.trash
alias rm=trash
alias r=trash
alias rl='ls ~/.trash'
alias ur=undel_file

undel_file()
{
	mv -i ~/.trash/$@ ./
}

trash()
{
	mv $@ ~/.trash
}

cleantrash()
{
	read -p "clear sure?[n]" confirm
	[ $confirm == 'y' ] || [ $confirm == 'Y' ] && /bin/rm -rf ~/.trash/*
}

rmd () {
	pandoc $1 | lynx -stdin
}

